name: mcp
description: A Model-Context-Protocal(MCP) Client implementation for Dart.
version: 1.0.0
repository: https://github.com/lollipopkit/mcp.dart

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  dio: ^5.8.0+1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  synchronized: ^3.3.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.4
  json_serializable: ^6.7.1
  lints: ^5.0.0
  test: ^1.24.0
